export type TermStatus = "good" | "watch" | "bad";

export interface TermExample {
  label: string;
  value: string;
  status: TermStatus;
  explanation: string;
  samplePoints: number[];
}

export interface GlossaryTerm {
  slug: string;
  title: string;
  shortLabel: string;
  category: "load" | "quality" | "power" | "battery" | "pv";
  summary: string;
  definition: string;
  whyItMatters: string;
  plainLanguage: string;
  unit: string;
  quickTake: string;
  goodExample: string;
  badExample: string;
  formula?: string;
  tooltipSummary: string;
  tooltipRange: string;
  heroKicker: string;
  faq: Array<{ question: string; answer: string }>;
  examples: TermExample[];
  relatedSlugs: string[];
}

export const GLOSSARY_CATEGORY_LABELS: Record<GlossaryTerm["category"], string> = {
  load: "Load & energy",
  quality: "Power quality",
  power: "Electrical efficiency",
  battery: "Battery strategy",
  pv: "Solar & overlap",
};

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    slug: "peak-demand",
    title: "Peak Demand",
    shortLabel: "Peak demand",
    category: "load",
    summary: "Peak demand is the highest electrical load reached during the measured period.",
    definition: "Peak demand is the maximum power value your site reaches in the selected time window. It is usually the value utilities care about when demand charges are part of the tariff.",
    whyItMatters: "A short but extreme load spike can cost more than a slightly higher average load. Peak demand tells you where battery peak shaving or operational staggering would help most.",
    plainLanguage: "Think of it as the single busiest moment in your energy profile.",
    unit: "kW",
    quickTake: "High peaks with low average load usually mean intermittent heavy equipment or poor staging.",
    goodExample: "A stable facility where the peak is only slightly above the daily average.",
    badExample: "A workshop that jumps from 20 kW to 95 kW for a few minutes whenever several machines start together.",
    formula: "Peak demand = max(load kW)",
    tooltipSummary: "Highest power value reached in the selected measurement period.",
    tooltipRange: "Good: close to average load. Bad: isolated spikes far above the baseline.",
    heroKicker: "Load economics",
    faq: [
      { question: "Why can one short spike matter so much?", answer: "Because many tariffs use the highest short interval, often 15 minutes, to calculate demand charges." },
      { question: "Does peak demand mean bad power quality?", answer: "No. It is a load behavior metric, not a voltage quality metric." },
    ],
    examples: [
      { label: "Stable production", value: "34 kW", status: "good", explanation: "Peak stays close to the average load, so the site is predictable.", samplePoints: [25, 26, 27, 28, 29, 30, 31, 32, 33, 34] },
      { label: "Watch load staging", value: "61 kW", status: "watch", explanation: "Peak is noticeably above the base load and worth checking against equipment schedules.", samplePoints: [18, 19, 20, 21, 22, 45, 61, 28, 24, 22] },
      { label: "Demand-charge risk", value: "96 kW", status: "bad", explanation: "Short peaks dominate the profile and likely create avoidable billing stress.", samplePoints: [16, 18, 17, 19, 21, 88, 96, 25, 20, 18] },
    ],
    relatedSlugs: ["average-load", "base-load", "battery-peak-shaving", "load-spikes"],
  },
  {
    slug: "average-load",
    title: "Average Load",
    shortLabel: "Average load",
    category: "load",
    summary: "Average load is the mean import power over the measured period.",
    definition: "Average load describes the typical power level the site draws during the dataset. It smooths out individual spikes and gives a better view of sustained demand.",
    whyItMatters: "Comparing average load with peak demand helps you see whether your site is steady or bursty. That difference drives peak-shaving value.",
    plainLanguage: "It answers: what is my site usually drawing, not just at the worst moment?",
    unit: "kW",
    quickTake: "Average load is the anchor that makes peaks, baseload, and PV overlap easier to interpret.",
    goodExample: "A cold store with a narrow spread between average and peak load.",
    badExample: "A site where average load is 9 kW but peaks hit 80 kW, meaning most of the cost comes from rare events.",
    tooltipSummary: "Typical import power level across the full time window.",
    tooltipRange: "Good: average and peak are relatively close. Bad: average is low but peak is extreme.",
    heroKicker: "Load profile",
    faq: [
      { question: "Can average load hide operational problems?", answer: "Yes. Average load can look healthy even if a site has costly short spikes." },
      { question: "Why is average load still useful?", answer: "Because it gives context for utilization, energy consumption, and the peak-to-average ratio." },
    ],
    examples: [
      { label: "Even process", value: "28 kW", status: "good", explanation: "Load is consistent and operational planning is predictable.", samplePoints: [27, 28, 28, 29, 28, 27, 28, 29, 28, 28] },
      { label: "Moderately variable", value: "19 kW", status: "watch", explanation: "Average load is reasonable but some peaks may still be worth managing.", samplePoints: [13, 15, 18, 21, 27, 24, 18, 16, 19, 20] },
      { label: "Misleadingly low", value: "9 kW", status: "bad", explanation: "Average looks small, but the true issue is hidden in sharp peaks.", samplePoints: [4, 5, 5, 6, 7, 42, 60, 8, 5, 4] },
    ],
    relatedSlugs: ["peak-demand", "base-load", "load-spikes"],
  },
  {
    slug: "total-energy",
    title: "Total Energy",
    shortLabel: "Energy",
    category: "load",
    summary: "Total energy is the accumulated electrical work consumed during the measured time window.",
    definition: "Total energy adds up all measured power over time and expresses the result in kilowatt-hours. It tells you how much electricity the site actually used across the selected period.",
    whyItMatters: "Energy is what usually drives volumetric electricity cost. It complements peak demand by showing how much consumption happened overall, not only at the highest moment.",
    plainLanguage: "It is the size of the full electricity bill bucket, not just the tallest spike.",
    unit: "kWh",
    quickTake: "High energy with low peaks suggests long operating hours. Low energy with huge peaks suggests short but expensive bursts.",
    goodExample: "A site with moderate total energy spread smoothly across many operating hours.",
    badExample: "A site with unexpectedly high overnight or weekend energy that points to waste outside production hours.",
    tooltipSummary: "Accumulated electricity use across the selected measurement window.",
    tooltipRange: "Good: aligned with operating hours. Bad: unexpectedly large consumption during idle time.",
    heroKicker: "Consumption volume",
    faq: [
      { question: "Can energy look normal while peak demand is a problem?", answer: "Yes. Energy and demand answer different questions: total use versus worst-case rate." },
      { question: "Why can energy still be high with a modest average load?", answer: "Because long runtime can add up even when the instantaneous load is not extreme." },
    ],
    examples: [
      { label: "Expected use", value: "680 kWh", status: "good", explanation: "Consumption lines up with the production schedule and drops cleanly when the site is quiet.", samplePoints: [14, 18, 22, 28, 31, 32, 30, 26, 20, 15] },
      { label: "Extended runtime", value: "980 kWh", status: "watch", explanation: "Energy volume is plausible but suggests longer-than-expected operating windows.", samplePoints: [16, 20, 25, 29, 33, 35, 34, 31, 27, 22] },
      { label: "Idle-time waste", value: "1,240 kWh", status: "bad", explanation: "The site keeps drawing substantial load even outside the productive part of the day.", samplePoints: [22, 24, 26, 28, 31, 33, 32, 30, 28, 25] },
    ],
    relatedSlugs: ["average-load", "base-load", "peak-demand"],
  },
  {
    slug: "base-load",
    title: "Base Load",
    shortLabel: "Base load",
    category: "load",
    summary: "Base load is the lower end of the sustained import profile when the site is mostly idle.",
    definition: "Base load is the persistent load that remains when production or activity drops. In this tool it is estimated from the lower part of positive import power values rather than from a single minimum sample.",
    whyItMatters: "A high base load suggests energy is being consumed continuously, often by HVAC, standby equipment, refrigeration, or always-on systems.",
    plainLanguage: "It is the load you cannot seem to get rid of, even in quiet periods.",
    unit: "kW",
    quickTake: "Reducing base load saves energy all day, not just during short peaks.",
    goodExample: "An office that drops to a low standby level at night and weekends.",
    badExample: "A building that still draws 18 kW overnight because equipment never fully powers down.",
    tooltipSummary: "Persistent low-end import load that remains during quiet periods.",
    tooltipRange: "Good: clearly lower than daytime average. Bad: unexpectedly high during idle periods.",
    heroKicker: "Energy leakage",
    faq: [
      { question: "Is base load the same as minimum load?", answer: "No. Minimum load can be a one-off dip. Base load aims to reflect a more representative lower operating level." },
      { question: "What usually drives high base load?", answer: "Cooling, compressed air leaks, pumps, standby systems, or systems left on out of habit." },
    ],
    examples: [
      { label: "Lean standby", value: "4 kW", status: "good", explanation: "The site falls to a low idle state outside active hours.", samplePoints: [4, 4, 4, 5, 6, 7, 8, 5, 4, 4] },
      { label: "Moderate overnight load", value: "11 kW", status: "watch", explanation: "There may be optimization potential in auxiliary systems.", samplePoints: [11, 11, 12, 13, 16, 18, 19, 14, 12, 11] },
      { label: "Always-on penalty", value: "19 kW", status: "bad", explanation: "Idle consumption stays too high and likely drives avoidable kWh cost.", samplePoints: [19, 19, 20, 21, 22, 24, 25, 22, 20, 19] },
    ],
    relatedSlugs: ["average-load", "peak-demand", "pv-generation"],
  },
  {
    slug: "power-factor",
    title: "Power Factor",
    shortLabel: "Power factor",
    category: "power",
    summary: "Power factor describes how effectively electrical current is being turned into useful real power.",
    definition: "Power factor compares real power to apparent power. A value near 1.00 means current and voltage are well aligned and most of the current contributes to useful work.",
    whyItMatters: "Low power factor can increase current, heating, and in some tariffs financial penalties. It often points to reactive loads or poor compensation.",
    plainLanguage: "It tells you how much of the electricity you pull is actually doing useful work.",
    unit: "",
    quickTake: "For import periods, values below about 0.90 deserve attention and values below 0.80 are usually a real problem.",
    goodExample: "A motor system with compensation holding PF near 0.98.",
    badExample: "A lightly loaded or poorly compensated system drifting to 0.72 during import periods.",
    tooltipSummary: "How efficiently current is converted into useful real power.",
    tooltipRange: "Good: ~0.95-1.00. Bad: below ~0.80 during meaningful import load.",
    heroKicker: "Electrical efficiency",
    faq: [
      { question: "Why is low PF filtered by load in this tool?", answer: "Because PF during export or near-zero load can look bad without representing an actionable problem." },
      { question: "Can solar export distort PF?", answer: "Yes. That is why the dashboard evaluates PF mainly during material import." },
    ],
    examples: [
      { label: "Healthy import PF", value: "0.98", status: "good", explanation: "Most current contributes to useful work and the site is electrically efficient.", samplePoints: [0.97, 0.98, 0.98, 0.99, 0.98, 0.97, 0.98, 0.99, 0.98, 0.98] },
      { label: "Borderline compensation", value: "0.88", status: "watch", explanation: "The site may benefit from better reactive compensation or load balancing.", samplePoints: [0.9, 0.89, 0.88, 0.87, 0.88, 0.89, 0.88, 0.87, 0.88, 0.89] },
      { label: "Penalty risk", value: "0.74", status: "bad", explanation: "Reactive current is high enough to create efficiency and tariff concerns.", samplePoints: [0.8, 0.78, 0.76, 0.74, 0.73, 0.74, 0.75, 0.74, 0.73, 0.74] },
    ],
    relatedSlugs: ["thd-current", "peak-demand", "battery-peak-shaving"],
  },
  {
    slug: "voltage-band",
    title: "Voltage Band",
    shortLabel: "Voltage",
    category: "quality",
    summary: "Voltage band shows whether supply voltage stays inside an acceptable operating range.",
    definition: "Voltage band describes the observed minimum, average, and maximum voltage across the dataset. It helps you see whether the supply is too low, too high, or stable around nominal.",
    whyItMatters: "Equipment reliability, motor torque, heating, and electronics behavior all depend on stable supply voltage.",
    plainLanguage: "It answers whether the incoming electrical pressure is staying where it should.",
    unit: "V",
    quickTake: "A narrow and centered band is healthy. A wide or shifted band needs attention.",
    goodExample: "Phase voltages holding tightly around 230 V.",
    badExample: "Frequent excursions down near 205 V or up above 253 V.",
    tooltipSummary: "Observed min, avg, and max voltage across the selected period.",
    tooltipRange: "Good: narrow band near nominal. Bad: repeated excursions outside the expected tolerance.",
    heroKicker: "Supply quality",
    faq: [
      { question: "Is a single short dip enough to panic?", answer: "Not always. The pattern and duration matter more than one isolated sample." },
      { question: "Why can average voltage look fine while risk still exists?", answer: "Because short over- or undervoltage events can be hidden by the mean." },
    ],
    examples: [
      { label: "Stable supply", value: "228-232 V", status: "good", explanation: "Voltage stays tight and centered around nominal.", samplePoints: [229, 230, 230, 231, 230, 229, 230, 231, 230, 230] },
      { label: "Noticeable spread", value: "221-239 V", status: "watch", explanation: "Still usable, but enough spread to justify monitoring sensitive loads.", samplePoints: [221, 224, 228, 232, 236, 239, 235, 231, 227, 223] },
      { label: "Out-of-range", value: "205-256 V", status: "bad", explanation: "The supply repeatedly moves beyond a comfortable operating zone.", samplePoints: [256, 248, 240, 220, 205, 214, 229, 243, 251, 246] },
    ],
    relatedSlugs: ["voltage-stability", "phase-imbalance", "frequency"],
  },
  {
    slug: "voltage-stability",
    title: "Voltage Stability",
    shortLabel: "Voltage stability",
    category: "quality",
    summary: "Voltage stability shows how tightly voltages cluster around their average value.",
    definition: "Voltage stability in this tool is expressed as coefficient of variation. Lower values mean the voltage is steady and does not wander much around its mean.",
    whyItMatters: "Stable voltage means fewer surprises for drives, electronics, and lighting. It is often a better comfort metric than raw min/max alone.",
    plainLanguage: "It measures how jumpy the voltage is.",
    unit: "%",
    quickTake: "Lower is better. A tiny percentage means a calm supply.",
    goodExample: "A grid connection varying by only a few tenths of a percent.",
    badExample: "A feeder where voltage drifts and oscillates enough to create flicker-like symptoms.",
    tooltipSummary: "How much voltage varies around its own average value.",
    tooltipRange: "Good: very low percentage. Bad: wide swings around the mean.",
    heroKicker: "Consistency",
    faq: [
      { question: "Can min and max be okay while stability is poor?", answer: "Yes. Frequent small oscillations can produce a weak stability score without huge absolute excursions." },
      { question: "Why is this useful with the voltage band?", answer: "Voltage band shows the outer bounds; stability shows how calm the signal was in between." },
    ],
    examples: [
      { label: "Calm supply", value: "0.3%", status: "good", explanation: "The voltage barely moves around its average.", samplePoints: [230, 230, 230, 231, 230, 230, 229, 230, 230, 230] },
      { label: "Variable feed", value: "1.6%", status: "watch", explanation: "Oscillations are visible and worth correlating with load or feeder behavior.", samplePoints: [226, 229, 233, 235, 232, 228, 225, 229, 233, 231] },
      { label: "Unsteady line", value: "3.8%", status: "bad", explanation: "Voltage motion is large enough to deserve investigation.", samplePoints: [220, 229, 241, 236, 222, 217, 231, 244, 235, 223] },
    ],
    relatedSlugs: ["voltage-band", "frequency", "phase-imbalance"],
  },
  {
    slug: "thd-voltage",
    title: "Voltage THD",
    shortLabel: "THD V",
    category: "quality",
    summary: "Voltage THD measures how distorted the voltage waveform is compared with a clean sine wave.",
    definition: "Total harmonic distortion for voltage shows how much harmonic content is riding on top of the fundamental voltage wave. Higher THD means the waveform shape is becoming less sinusoidal.",
    whyItMatters: "High voltage THD can point to harmonic stress on the network and can affect sensitive equipment, transformers, and losses.",
    plainLanguage: "It tells you whether the voltage wave is smooth or misshapen.",
    unit: "%",
    quickTake: "Low single-digit THD is common. Higher values suggest real harmonic pollution or filter issues.",
    goodExample: "A clean supply where voltage THD stays around 2-3%.",
    badExample: "A bus with voltage THD climbing above 8%, especially during heavy nonlinear loading.",
    tooltipSummary: "How distorted the voltage waveform is relative to a pure sine wave.",
    tooltipRange: "Good: low single digits. Bad: persistent high distortion above typical limits.",
    heroKicker: "Waveform quality",
    faq: [
      { question: "Why can THD V be unavailable?", answer: "Some meters export zeroes when voltage harmonic measurement is not actually configured." },
      { question: "Is THD V the same as current THD?", answer: "No. Voltage THD describes network distortion, while current THD describes the load current shape." },
    ],
    examples: [
      { label: "Clean waveform", value: "2.4%", status: "good", explanation: "Voltage waveform stays close to a clean sine.", samplePoints: [2.1, 2.2, 2.4, 2.6, 2.5, 2.3, 2.4, 2.5, 2.3, 2.4] },
      { label: "Elevated distortion", value: "5.9%", status: "watch", explanation: "Distortion is noticeable and worth correlating with nonlinear loads.", samplePoints: [4.2, 4.8, 5.1, 5.6, 5.9, 5.5, 5.2, 5.6, 5.8, 5.7] },
      { label: "Harmonic stress", value: "9.1%", status: "bad", explanation: "Voltage distortion is high enough to justify harmonic investigation.", samplePoints: [6.8, 7.4, 8.2, 8.8, 9.1, 8.9, 8.3, 8.7, 9.0, 8.8] },
    ],
    relatedSlugs: ["thd-current", "power-factor", "neutral-current"],
  },
  {
    slug: "thd-current",
    title: "Current THD",
    shortLabel: "THD I",
    category: "quality",
    summary: "Current THD measures how distorted load current is compared with a clean sine wave.",
    definition: "Current THD shows the harmonic content in current drawn by the load. High values are common with nonlinear equipment such as drives, UPS systems, LED drivers, and rectifiers.",
    whyItMatters: "High current THD can raise neutral currents, increase losses, and contribute to voltage distortion if the network is weak.",
    plainLanguage: "It tells you how messy the current waveform coming from your loads has become.",
    unit: "%",
    quickTake: "High current THD at low load is less useful. High THD during meaningful load is the real signal.",
    goodExample: "A largely linear process with current THD under 10% under load.",
    badExample: "A heavily nonlinear load bank driving current THD past 25% during operation.",
    tooltipSummary: "How distorted the current waveform is under actual load.",
    tooltipRange: "Good: low to moderate under load. Bad: persistently high during meaningful current draw.",
    heroKicker: "Load distortion",
    faq: [
      { question: "Why does the dashboard focus on THD under load?", answer: "Because high THD at tiny current can look dramatic without representing a material operating problem." },
      { question: "Can high THD I exist with okay voltage?", answer: "Yes. A strong supply can absorb distorted current without large THD V growth." },
    ],
    examples: [
      { label: "Linear load mix", value: "8%", status: "good", explanation: "Current waveform stays reasonably clean during operation.", samplePoints: [6, 7, 8, 8, 9, 8, 7, 8, 8, 7] },
      { label: "Nonlinear but manageable", value: "17%", status: "watch", explanation: "The site should be watched for filters, neutral current, and load mix effects.", samplePoints: [12, 14, 15, 17, 18, 17, 16, 17, 18, 17] },
      { label: "Severe current distortion", value: "29%", status: "bad", explanation: "Harmonic current is high enough to become a real engineering issue.", samplePoints: [20, 22, 25, 27, 29, 28, 27, 28, 29, 28] },
    ],
    relatedSlugs: ["thd-voltage", "neutral-current", "power-factor"],
  },
  {
    slug: "phase-imbalance",
    title: "Phase Imbalance",
    shortLabel: "Imbalance",
    category: "quality",
    summary: "Phase imbalance shows how unevenly the three phase voltages deviate from each other.",
    definition: "Phase imbalance measures the maximum deviation from the average phase voltage, expressed as a percentage. It reveals how symmetrical the three-phase supply is.",
    whyItMatters: "High imbalance can overheat motors, reduce efficiency, and indicate poor distribution of single-phase loads or supply issues.",
    plainLanguage: "It tells you whether the three phases are sharing the work evenly.",
    unit: "%",
    quickTake: "Small percentages are healthy. Higher values deserve investigation before motors or transformers suffer.",
    goodExample: "A well-balanced feeder with phases within a tight voltage spread.",
    badExample: "One phase sagging much lower than the others because of uneven single-phase loading.",
    tooltipSummary: "How uneven the three phase voltages are relative to each other.",
    tooltipRange: "Good: low percentage. Bad: sustained imbalance above a few percent.",
    heroKicker: "Three-phase symmetry",
    faq: [
      { question: "Does imbalance always come from the utility?", answer: "No. It often comes from uneven internal loading across phases." },
      { question: "Why do motors care so much?", answer: "Because small voltage imbalance can create disproportionately high current imbalance and heating." },
    ],
    examples: [
      { label: "Balanced phases", value: "0.6%", status: "good", explanation: "The three phases track closely and behave as a healthy set.", samplePoints: [0.4, 0.5, 0.6, 0.6, 0.7, 0.6, 0.5, 0.6, 0.6, 0.5] },
      { label: "Moderate asymmetry", value: "2.8%", status: "watch", explanation: "Uneven single-phase loads or feeder conditions should be checked.", samplePoints: [1.6, 1.9, 2.1, 2.4, 2.8, 2.6, 2.3, 2.5, 2.7, 2.6] },
      { label: "Motor stress risk", value: "5.7%", status: "bad", explanation: "The phase spread is large enough to justify immediate engineering review.", samplePoints: [3.8, 4.2, 4.8, 5.1, 5.7, 5.4, 5.0, 5.2, 5.5, 5.4] },
    ],
    relatedSlugs: ["voltage-band", "voltage-stability", "neutral-current"],
  },
  {
    slug: "frequency",
    title: "Frequency",
    shortLabel: "Frequency",
    category: "quality",
    summary: "Frequency measures how fast the AC waveform oscillates around its nominal value.",
    definition: "Frequency is the electrical grid oscillation rate, usually centered near 50 Hz or 60 Hz depending on the region. Deviations are typically small but can reveal supply instability or islanding conditions.",
    whyItMatters: "Most sites expect frequency to stay very close to nominal. Large excursions are unusual and important when present.",
    plainLanguage: "It is the heartbeat speed of the AC system.",
    unit: "Hz",
    quickTake: "Tiny deviations are normal. Sustained visible movement is a signal worth keeping.",
    goodExample: "A grid that stays within a few hundredths of a hertz around nominal.",
    badExample: "Frequency drifting enough to indicate unstable generation or isolated operation.",
    tooltipSummary: "Grid oscillation rate relative to the nominal system frequency.",
    tooltipRange: "Good: very close to nominal. Bad: repeated or sustained visible excursions.",
    heroKicker: "Grid heartbeat",
    faq: [
      { question: "Why is frequency often the least dramatic metric?", answer: "Because strong utility grids regulate frequency tightly most of the time." },
      { question: "When does frequency become urgent?", answer: "When excursions are large, sustained, or correlated with operational disturbances." },
    ],
    examples: [
      { label: "Tight control", value: "50.00 Hz", status: "good", explanation: "The grid stays essentially on target.", samplePoints: [49.99, 50.0, 50.01, 50.0, 50.0, 49.99, 50.0, 50.01, 50.0, 50.0] },
      { label: "Noticeable drift", value: "49.72-50.28 Hz", status: "watch", explanation: "Movement is larger than typical and worth correlating with site events.", samplePoints: [49.8, 49.9, 50.0, 50.1, 50.2, 50.28, 50.18, 50.0, 49.86, 49.72] },
      { label: "Instability signal", value: "49.2-50.8 Hz", status: "bad", explanation: "Excursions are large enough to indicate a serious supply event.", samplePoints: [49.2, 49.4, 49.8, 50.3, 50.8, 50.6, 50.1, 49.7, 49.4, 49.3] },
    ],
    relatedSlugs: ["voltage-band", "voltage-stability"],
  },
  {
    slug: "sample-interval",
    title: "Sample Interval",
    shortLabel: "Sample interval",
    category: "load",
    summary: "Sample interval is the time gap between consecutive measurements in the dataset.",
    definition: "Sample interval tells you how often the meter recorded a new row. Short intervals preserve short spikes and disturbances, while longer intervals smooth them out.",
    whyItMatters: "Resolution controls what the analysis can see. A 1-second file can reveal transients that disappear in a 15-minute dataset.",
    plainLanguage: "It is the sharpness setting of your measurement history.",
    unit: "s / min",
    quickTake: "Shorter intervals show more detail. Longer intervals are fine for trends but can hide short events.",
    goodExample: "A dataset sampled every few seconds or every minute for operational diagnostics.",
    badExample: "A coarse interval that averages away the very spikes or dips you need to understand.",
    tooltipSummary: "Time between measurement rows, which defines how much detail the dataset can preserve.",
    tooltipRange: "Good: fine enough for the question. Bad: so coarse that important short events disappear.",
    heroKicker: "Data resolution",
    faq: [
      { question: "Does a longer interval make the data wrong?", answer: "No. It makes it less detailed. The right interval depends on the analysis goal." },
      { question: "Why do spike counts depend on interval?", answer: "Because averaging over longer windows can compress or completely hide short events." },
    ],
    examples: [
      { label: "Diagnostic detail", value: "10 s", status: "good", explanation: "The dataset can resolve short operational changes clearly.", samplePoints: [12, 12, 14, 28, 13, 12, 25, 12, 12, 13] },
      { label: "Trend-friendly", value: "1 min", status: "watch", explanation: "Useful for site-level behavior, but some short transients may already be smoothed.", samplePoints: [12, 13, 17, 22, 16, 14, 19, 14, 13, 13] },
      { label: "Too coarse for spikes", value: "15 min", status: "bad", explanation: "Short load events are heavily averaged and operational root causes become harder to isolate.", samplePoints: [14, 15, 16, 18, 17, 16, 18, 17, 16, 15] },
    ],
    relatedSlugs: ["peak-demand", "load-spikes", "average-load"],
  },
  {
    slug: "load-spikes",
    title: "Load Spikes",
    shortLabel: "Spikes",
    category: "load",
    summary: "Load spikes are short periods where power rises far above the site’s usual import level.",
    definition: "Load spikes are short contiguous events above the site’s typical base or average load. The dashboard groups them into spike events rather than treating every high sample independently.",
    whyItMatters: "Spikes are often what turn a reasonable energy user into an expensive demand-charge customer.",
    plainLanguage: "They are the sudden surges that break an otherwise normal load pattern.",
    unit: "kW",
    quickTake: "The more often spikes overlap with 15-minute billing windows, the more money they can cost.",
    goodExample: "A site with no distinct spike events or only very small transient rises.",
    badExample: "Repeated surges from compressors, ovens, or machine starts that punch far above the baseload.",
    tooltipSummary: "Short periods where load rises sharply above the site’s usual level.",
    tooltipRange: "Good: none or few small events. Bad: frequent or extreme spikes that hit billing windows.",
    heroKicker: "Transient load behavior",
    faq: [
      { question: "Are spikes always bad?", answer: "Not always. Some processes naturally spike. The question is whether they are avoidable or too expensive." },
      { question: "Why group spikes into events?", answer: "Because operators act on events, not isolated samples." },
    ],
    examples: [
      { label: "Flat profile", value: "0 events", status: "good", explanation: "The site is steady and does not show problematic surges.", samplePoints: [18, 18, 19, 19, 18, 18, 19, 18, 18, 19] },
      { label: "Operational surges", value: "4 events", status: "watch", explanation: "There are identifiable load events worth investigating.", samplePoints: [10, 11, 12, 32, 35, 14, 12, 30, 34, 13] },
      { label: "Demand-charge driver", value: "11 events", status: "bad", explanation: "Spike behavior is frequent enough to shape both billing and equipment stress.", samplePoints: [9, 10, 46, 58, 12, 10, 49, 61, 11, 10] },
    ],
    relatedSlugs: ["peak-demand", "battery-peak-shaving", "average-load"],
  },
  {
    slug: "battery-peak-shaving",
    title: "Battery Peak Shaving",
    shortLabel: "Battery",
    category: "battery",
    summary: "Battery peak shaving uses stored energy to reduce short high-demand periods.",
    definition: "Battery peak shaving means discharging a battery during demand peaks so the grid sees a lower load profile. In this tool the recommendation is based primarily on 15-minute demand reduction potential.",
    whyItMatters: "It can reduce demand charges without changing production if the peaks are short and predictable enough.",
    plainLanguage: "It is using a battery as a buffer so the grid never sees your worst spikes.",
    unit: "kW/kWh",
    quickTake: "It works best when peaks are sharp, repetitive, and much higher than the normal load.",
    goodExample: "A site with short repetitive peaks that can be shaved by a reasonably sized battery.",
    badExample: "A flat continuous high load where a battery would need to be huge to make a difference.",
    tooltipSummary: "Recommended battery size for reducing short peak-demand windows.",
    tooltipRange: "Good candidate: sharp, repetitive peaks. Weak candidate: flat load with little peak separation.",
    heroKicker: "Flexibility asset",
    faq: [
      { question: "Why does the tool focus on 15-minute demand?", answer: "Because that is how many demand tariffs are billed." },
      { question: "Can a battery solve high base load?", answer: "No. Batteries are better at peaks than at all-day inefficiency." },
    ],
    examples: [
      { label: "Strong candidate", value: "180 kW / 260 kWh", status: "good", explanation: "Peak windows are sharp enough that a practical battery can materially reduce billed demand.", samplePoints: [20, 22, 24, 80, 110, 28, 24, 90, 120, 26] },
      { label: "Mixed case", value: "95 kW / 190 kWh", status: "watch", explanation: "There is value, but the economics depend on tariff and operational flexibility.", samplePoints: [26, 28, 34, 52, 60, 38, 31, 48, 58, 34] },
      { label: "Weak candidate", value: "22 kW / 420 kWh", status: "bad", explanation: "Load is too flat, so battery energy needs rise faster than savings.", samplePoints: [48, 49, 50, 51, 52, 51, 50, 49, 50, 51] },
    ],
    relatedSlugs: ["peak-demand", "load-spikes", "pv-generation", "residual-load"],
  },
  {
    slug: "neutral-current",
    title: "Neutral Current",
    shortLabel: "Neutral I",
    category: "quality",
    summary: "Neutral current is the current flowing in the neutral conductor of a three-phase system.",
    definition: "Neutral current can rise when single-phase loads are unbalanced or when harmonic-rich loads create triplen harmonics that add in the neutral.",
    whyItMatters: "Unexpectedly high neutral current can indicate imbalance, harmonics, overheating risk, or poor load distribution.",
    plainLanguage: "It tells you how much return current is piling up in the neutral path.",
    unit: "A",
    quickTake: "Moderate neutral current is normal. High neutral current relative to phase current deserves explanation.",
    goodExample: "A balanced site where neutral current stays well below the phase currents.",
    badExample: "A harmonic-rich panel where neutral current grows much larger than expected.",
    tooltipSummary: "Current flowing in the neutral conductor relative to phase loading.",
    tooltipRange: "Good: modest relative to phase current. Bad: unexpectedly high or rising with harmonic stress.",
    heroKicker: "Return-path stress",
    faq: [
      { question: "Can a balanced system still have neutral current?", answer: "Yes, but it is usually small compared with problematic cases." },
      { question: "Why do harmonics matter here?", answer: "Triplen harmonics can sum in the neutral instead of canceling." },
    ],
    examples: [
      { label: "Balanced return path", value: "6 A", status: "good", explanation: "Neutral current stays comfortably below phase currents.", samplePoints: [4, 5, 5, 6, 6, 5, 5, 6, 6, 5] },
      { label: "Worth checking", value: "18 A", status: "watch", explanation: "The neutral is carrying enough current to review phase balance and harmonic content.", samplePoints: [10, 12, 14, 16, 18, 17, 16, 17, 18, 17] },
      { label: "Potential overheating risk", value: "33 A", status: "bad", explanation: "Neutral loading is high enough to indicate a real design or harmonic issue.", samplePoints: [20, 22, 25, 28, 33, 31, 29, 30, 32, 31] },
    ],
    relatedSlugs: ["phase-imbalance", "thd-current", "power-factor"],
  },
  {
    slug: "pv-generation",
    title: "PV Generation",
    shortLabel: "PV energy",
    category: "pv",
    summary: "PV generation is the electrical energy produced by the solar system during the overlapping measurement period.",
    definition: "PV generation in this tool is a separate normalized time series aligned to the measurement window. It shows what the solar array is producing, independent of the load measurements.",
    whyItMatters: "It gives context for self-consumption, surplus export potential, and how much of the site load could be covered locally.",
    plainLanguage: "It is the solar power available to offset site demand.",
    unit: "kWh",
    quickTake: "High PV generation is only part of the story. The overlap with site load determines how useful it is.",
    goodExample: "PV output lining up with daytime process loads so most generation is used on site.",
    badExample: "Large PV output arriving when the site is mostly idle, creating surplus rather than internal use.",
    tooltipSummary: "Solar energy produced during the part of the PV series that overlaps the measurement window.",
    tooltipRange: "Good: strong overlap with demand. Bad: lots of production but little coincident load.",
    heroKicker: "On-site generation",
    faq: [
      { question: "Why is PV treated as a sidecar dataset?", answer: "Because it should enrich the load analysis without changing the original measurement truth." },
      { question: "Does the tool interpolate PV outside overlap?", answer: "No. It only uses the overlapping time window." },
    ],
    examples: [
      { label: "High daytime overlap", value: "420 kWh", status: "good", explanation: "Solar production lines up with the main operating hours.", samplePoints: [0, 2, 6, 18, 34, 42, 38, 26, 10, 2] },
      { label: "Useful but partial", value: "210 kWh", status: "watch", explanation: "PV contributes meaningfully but does not align with all demand windows.", samplePoints: [0, 1, 4, 12, 20, 24, 18, 9, 3, 0] },
      { label: "Poor coincidence", value: "390 kWh", status: "bad", explanation: "Production is high, but much of it arrives when the site is lightly loaded.", samplePoints: [0, 4, 12, 26, 38, 40, 24, 8, 1, 0] },
    ],
    relatedSlugs: ["self-consumption", "surplus-energy", "residual-load", "battery-peak-shaving"],
  },
  {
    slug: "self-consumption",
    title: "Self-Consumption Potential",
    shortLabel: "Self-use",
    category: "pv",
    summary: "Self-consumption potential is the portion of PV generation that could directly serve on-site load.",
    definition: "In this tool self-consumption potential is estimated as the overlapping minimum of site load and PV generation at each matched sample.",
    whyItMatters: "It is usually the most valuable part of solar output because it offsets purchased electricity directly.",
    plainLanguage: "It is the slice of solar energy you can use yourself instead of exporting.",
    unit: "kWh",
    quickTake: "High PV generation is nice. High self-consumption is usually more valuable.",
    goodExample: "Most solar output is consumed by simultaneous daytime demand.",
    badExample: "Only a small fraction of PV is used on site because production arrives when loads are low.",
    tooltipSummary: "Estimated PV energy that coincides with and can directly cover on-site demand.",
    tooltipRange: "Good: large share of PV is used on site. Bad: most PV misses the load window.",
    heroKicker: "Coincidence value",
    faq: [
      { question: "Is this a billing-grade self-consumption number?", answer: "No. It is an analytical estimate based on the aligned datasets." },
      { question: "Can storage improve it?", answer: "Yes. Batteries can shift PV energy into later demand periods." },
    ],
    examples: [
      { label: "Strong coincidence", value: "82%", status: "good", explanation: "The majority of solar output lands directly on active load.", samplePoints: [0, 1, 4, 9, 16, 22, 19, 12, 4, 1] },
      { label: "Moderate match", value: "54%", status: "watch", explanation: "There is useful overlap, but timing gaps remain.", samplePoints: [0, 1, 3, 7, 10, 12, 10, 6, 2, 1] },
      { label: "Low direct use", value: "23%", status: "bad", explanation: "Most PV production is arriving when the site cannot absorb it.", samplePoints: [0, 0, 1, 3, 5, 6, 4, 2, 0, 0] },
    ],
    relatedSlugs: ["pv-generation", "surplus-energy", "residual-load", "battery-peak-shaving"],
  },
  {
    slug: "surplus-energy",
    title: "Surplus Energy",
    shortLabel: "Surplus",
    category: "pv",
    summary: "Surplus energy is PV generation that exceeds the coincident site load.",
    definition: "Surplus energy in this dashboard is the estimated energy amount where aligned PV generation is greater than aligned load, creating excess production potential.",
    whyItMatters: "Surplus can be exported, curtailed, or shifted with storage. It tells you where PV value is being left on the table.",
    plainLanguage: "It is the solar energy you have available after your own site needs are already covered.",
    unit: "kWh",
    quickTake: "Some surplus is fine. Persistent large surplus suggests timing mismatch or storage opportunity.",
    goodExample: "A site with little surplus because most PV is absorbed internally.",
    badExample: "A site exporting a large midday block because production far exceeds daytime demand.",
    tooltipSummary: "Estimated PV energy remaining after coincident on-site demand is covered.",
    tooltipRange: "Good: low or intentional. Bad: large recurring excess without a clear strategy.",
    heroKicker: "Export opportunity",
    faq: [
      { question: "Is surplus always bad?", answer: "No. It can be fine if export tariffs are attractive or the design intent is export." },
      { question: "What usually reduces surplus?", answer: "Load shifting, storage, or reshaping operational timing." },
    ],
    examples: [
      { label: "Minimal export", value: "18 kWh", status: "good", explanation: "Most solar output is used locally.", samplePoints: [0, 0, 0, 1, 2, 3, 2, 1, 0, 0] },
      { label: "Noticeable midday excess", value: "96 kWh", status: "watch", explanation: "There is room to improve alignment or monetize exports better.", samplePoints: [0, 0, 1, 3, 7, 12, 10, 5, 1, 0] },
      { label: "Large mismatch", value: "240 kWh", status: "bad", explanation: "PV output substantially outruns on-site demand for recurring periods.", samplePoints: [0, 1, 4, 9, 18, 25, 22, 11, 3, 0] },
    ],
    relatedSlugs: ["pv-generation", "self-consumption", "battery-peak-shaving"],
  },
  {
    slug: "residual-load",
    title: "Residual Load",
    shortLabel: "Residual load",
    category: "pv",
    summary: "Residual load is the estimated site load that remains after subtracting coincident PV generation.",
    definition: "Residual load is calculated as aligned load minus aligned PV generation. Positive values mean the site still needs grid import. Negative values suggest export or overproduction relative to load.",
    whyItMatters: "Residual load shows how the load profile changes once solar is applied. It is one of the clearest ways to see solar’s operational impact.",
    plainLanguage: "It is the part of the load that solar has not covered yet.",
    unit: "kW",
    quickTake: "Residual load connects PV performance directly to grid dependency.",
    goodExample: "PV trims the daytime profile while residual load remains smooth and positive.",
    badExample: "Residual load flips sharply negative at noon, meaning PV is badly mismatched to demand.",
    tooltipSummary: "Estimated remaining site load after coincident PV generation is subtracted.",
    tooltipRange: "Good: lower positive daytime load. Bad: deep negative windows or no visible reduction.",
    heroKicker: "Net demand view",
    faq: [
      { question: "Does residual load replace the original measurement?", answer: "No. It is a comparison overlay, not a new source of truth." },
      { question: "What does negative residual load mean?", answer: "It means PV generation exceeds the coincident measured load at that moment." },
    ],
    examples: [
      { label: "Solar trims imports", value: "6-18 kW", status: "good", explanation: "PV lowers daytime import without overshooting too often.", samplePoints: [18, 17, 15, 12, 8, 6, 7, 10, 14, 17] },
      { label: "Mixed effect", value: "2-22 kW", status: "watch", explanation: "PV helps, but some periods still see high residual demand.", samplePoints: [22, 20, 18, 14, 8, 4, 7, 13, 18, 21] },
      { label: "Mismatch and export", value: "-12 to 24 kW", status: "bad", explanation: "Residual load crosses deeply negative, showing a strong timing mismatch.", samplePoints: [24, 20, 16, 8, -4, -12, -8, 3, 14, 21] },
    ],
    relatedSlugs: ["pv-generation", "self-consumption", "surplus-energy", "battery-peak-shaving"],
  },
];

export const GLOSSARY_TERM_MAP = new Map(GLOSSARY_TERMS.map((term) => [term.slug, term]));

export function getGlossaryTerm(slug: string): GlossaryTerm | undefined {
  return GLOSSARY_TERM_MAP.get(slug);
}

export const KPI_GLOSSARY_LINKS: Record<string, string> = {
  peakDemand: "peak-demand",
  averageLoad: "average-load",
  energy: "total-energy",
  voltage: "voltage-band",
  powerFactor: "power-factor",
  thdCurrent: "thd-current",
  imbalance: "phase-imbalance",
  spikes: "load-spikes",
  frequency: "frequency",
  sampleInterval: "sample-interval",
  battery: "battery-peak-shaving",
  neutralCurrent: "neutral-current",
  pvEnergy: "pv-generation",
  selfUse: "self-consumption",
  surplus: "surplus-energy",
  residualLoad: "residual-load",
  baseLoad: "base-load",
  voltageStability: "voltage-stability",
  thdVoltage: "thd-voltage",
};
